build-timesketch:
	docker build -t dmitryzagr/timesketch:20180613 -f Dockerfile .. 
push-timesketch:
	docker push dmitryzagr/timesketch:20180613

build-timesketch-elasticsearch:
	docker build -t dmitryzagr/timesketch-elasticsearch:20180613 -f ../contrib/Dockerfile ../contrib
push-timesketch-elasticsearch:
	docker push dmitryzagr/timesketch-elasticsearch:20180613
